"""ne4

Revision ID: 0305e40d88cd
Revises: a61fb944056c
Create Date: 2021-07-23 08:31:29.206497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0305e40d88cd'
down_revision = 'a61fb944056c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('electionOfficialJmbg', sa.String(length=13), nullable=False))
    op.add_column('vote', sa.Column('ballotGuid', sa.Integer(), nullable=True))
    op.drop_column('vote', 'guid')
    op.drop_column('vote', 'jmbg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('jmbg', mysql.VARCHAR(length=13), nullable=False))
    op.add_column('vote', sa.Column('guid', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vote', 'ballotGuid')
    op.drop_column('vote', 'electionOfficialJmbg')
    # ### end Alembic commands ###
