"""new9

Revision ID: 072bea294fd6
Revises: cd3f4701a1b7
Create Date: 2021-07-23 14:05:20.806091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '072bea294fd6'
down_revision = 'cd3f4701a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('ballotGuid', sa.String(length=256), nullable=True))
    op.drop_column('vote', 'ballotGui')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('ballotGui', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=256), nullable=True))
    op.drop_column('vote', 'ballotGuid')
    # ### end Alembic commands ###
