"""new

Revision ID: 4aecaed3fc0c
Revises: 8e0ff9974270
Create Date: 2021-07-22 23:34:49.087885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aecaed3fc0c'
down_revision = '8e0ff9974270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('reason', sa.String(length=256), nullable=True))
    op.add_column('vote', sa.Column('poll', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'poll')
    op.drop_column('vote', 'reason')
    # ### end Alembic commands ###
