"""2

Revision ID: 504bbcc672be
Revises: 1298f114f710
Create Date: 2021-07-20 15:53:33.977486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504bbcc672be'
down_revision = '1298f114f710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('individual', sa.Boolean(), nullable=False))
    op.drop_column('participants', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('type', mysql.VARCHAR(length=1), nullable=False))
    op.drop_column('participants', 'individual')
    # ### end Alembic commands ###
