"""new8

Revision ID: 8920ef3ff8a4
Revises: 0305e40d88cd
Create Date: 2021-07-23 13:50:30.560689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8920ef3ff8a4'
down_revision = '0305e40d88cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'ballotGuid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'ballotGuid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
