"""Migracija2

Revision ID: 8e0ff9974270
Revises: 504bbcc672be
Create Date: 2021-07-20 22:42:34.770452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e0ff9974270'
down_revision = '504bbcc672be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('individual', sa.Boolean(), nullable=False))
    op.drop_column('election', 'type')
    op.add_column('vote', sa.Column('IdElection', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vote', 'election', ['IdElection'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_column('vote', 'IdElection')
    op.add_column('election', sa.Column('type', mysql.VARCHAR(length=1), nullable=False))
    op.drop_column('election', 'individual')
    # ### end Alembic commands ###
