"""new4

Revision ID: a61fb944056c
Revises: 9718931ffcf0
Create Date: 2021-07-23 00:14:56.398428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a61fb944056c'
down_revision = '9718931ffcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election_participant', 'guid')
    op.add_column('vote', sa.Column('guid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'guid')
    op.add_column('election_participant', sa.Column('guid', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
