"""ner

Revision ID: cd3f4701a1b7
Revises: 8920ef3ff8a4
Create Date: 2021-07-23 13:52:29.798081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd3f4701a1b7'
down_revision = '8920ef3ff8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('ballotGui', sa.String(length=256), nullable=False))
    op.drop_column('vote', 'ballotGuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('ballotGuid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vote', 'ballotGui')
    # ### end Alembic commands ###
