"""new migration

Revision ID: a2774f3d6635
Revises: b7fe0368fce0
Create Date: 2021-07-19 20:43:56.138370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2774f3d6635'
down_revision = 'b7fe0368fce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jmbg', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'users', ['jmbg'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'jmbg')
    # ### end Alembic commands ###
