version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  votingstation:
    image: votingstation
    environment:
       - TZ= Europe/Belgrade
       - DATABASE_URL=electionDB
       - MYSQL_ROOT_PASSWORD=root
    ports:
       - 5003:5003
    networks:
      -mynet
networks:
  mynet:




